### ISSUE TITLE
Missing declaration file for module 'xstate'

### ISSUE THREAD

**Issue by Stouffi** [davidkpiano/xstate#21]
I installed the latest version 1.2.1 to try xstate in a new project written in typescript and I'm getting an issue when importing something from the module.

I use this import statement as indicated in the README

`import { Machine } from 'xstate';`

But in the TS compiler output, I get "ERROR in src/app/app.machine.ts(1,25): error TS7016: Could not find a declaration file for module 'xstate'. '/home/stephane/Libertrip/ModelV2/node_modules/xstate/dist/xstate.js' implicitly has an 'any' type."

It seems the built library lacks a declaration file to allow imports of all members using the module name.
One possible workaround is to specify the path to the file declaring the member

`import xstate from 'xstate/lib/index';`

Then I gain access to `xstate.Machine` which is correctly typed.

For convenience, would it be possible to fix this?

**Comment by davidkpiano** [comment]
This should work on the beta 2.0 version (releasing soon, in December): just `npm install xstate@beta` 😄
