### ISSUE TITLE
Various typing errors after TypeScript upgrade 3.5 => 3.8

### ISSUE THREAD

**Issue by RafaelKr** [davidkpiano/xstate#1389]
**Description**
I got a Machine which is working completely fine. But after an update from TypeScript 3.5.3 to 3.8.3 it throws various typing errors when using the `assign` action on `entry` or `actions`.

Am I doing something unintended or is there a bug with the typings?
At least I can confirm it's working as expected.

**Expected Result**
No typing errors as it was with TypeScript 3.5.3

**Actual Result**
```
[npm] src/app/shared/services/push-notification/push-notification.service.ts:88:3 - error TS2322: Type 'Interpreter<Record<string, any>, any, EventObject, { value: any; context: Record<string, any>; }>' is not assignable to type 'Interpreter<PushStatusContext, PushStatusSchema, PushStatusEvent, { value: any; context: PushStatusContext; }>'.
[npm]   The types of 'machine.config.initial' are incompatible between these types.
[npm]     Type 'string | number | symbol' is not assignable to type '"deregistered" | "registered"'.
[npm]       Type 'string' is not assignable to type '"deregistered" | "registered"'.
[npm] 88        this.pushStatusMachine = createPushStatusMachine(
[npm]           ~~~~~~~~~~~~~~~~~~~~~~
[npm] src/app/shared/services/push-notification/push-notification.state.ts:53:8 - error TS2322: Type 'AssignAction<{ isToggling: false; }, PushStatusEvent>' is not assignable to type 'SingleOrArray<Action<PushStatusContext, PushStatusEvent>>'.
[npm]   Type 'AssignAction<{ isToggling: false; }, PushStatusEvent>' is not assignable to type 'string'.
[npm] 53                                                entry: assign({
[npm]                                                   ~~~~~
[npm]   node_modules/xstate/lib/types.d.ts:304:5
[npm]     304     entry?: Actions<TContext, TEvent>;
[npm]             ~~~~~
[npm]     The expected type comes from property 'entry' which is declared here on type 'StateNodeConfig<PushStatusContext, {}, PushStatusEvent>'
[npm] src/app/shared/services/push-notification/push-notification.state.ts:62:8 - error TS2322: Type 'AssignAction<{ isToggling: true; shouldBeEnabled: true; }, PushStatusEvent>' is not assignable to type 'SingleOrArray<Action<PushStatusContext, PushStatusEvent>>'.
[npm]   Type 'AssignAction<{ isToggling: true; shouldBeEnabled: true; }, PushStatusEvent>' is not assignable to type 'string'.
[npm] 62                                                entry: assign({
[npm]                                                   ~~~~~
[npm]   node_modules/xstate/lib/types.d.ts:304:5
[npm]     304     entry?: Actions<TContext, TEvent>;
[npm]             ~~~~~
[npm]     The expected type comes from property 'entry' which is declared here on type 'StateNodeConfig<PushStatusContext, {}, PushStatusEvent>'
[npm] src/app/shared/services/push-notification/push-notification.state.ts:66:8 - error TS2322: Type '{ id: string; src: () => Promise<any>; onDone: { actions: AssignAction<{ isEnabled: true; }, DoneInvokeEvent<any>>; target: string; }; onError: string; }' is not assignable to type 'SingleOrArray<StateMachine<any, any, any, { value: any; context: any; }> | InvokeConfig<PushStatusContext, PushStatusEvent>>'.
[npm]   Types of property 'onDone' are incompatible.
[npm]     Type '{ actions: AssignAction<{ isEnabled: true; }, DoneInvokeEvent<any>>; target: string; }' is not assignable to type 'string | TransitionConfig<PushStatusContext, DoneInvokeEvent<any>> | TransitionConfig<PushStatusContext, DoneInvokeEvent<...>>[]'.
[npm]       Types of property 'actions' are incompatible.
[npm]         Type 'AssignAction<{ isEnabled: true; }, DoneInvokeEvent<any>>' is not assignable to type 'SingleOrArray<Action<PushStatusContext, DoneInvokeEvent<any>>>'.
[npm]           Type 'AssignAction<{ isEnabled: true; }, DoneInvokeEvent<any>>' is not assignable to type 'string'.
[npm] 66                                                invoke: {
[npm]                                                   ~~~~~~
[npm]   node_modules/xstate/lib/types.d.ts:290:5
[npm]     290     invoke?: SingleOrArray<InvokeConfig<TContext, TEvent> | StateMachine<any, any, any>>;
[npm]             ~~~~~~
[npm]     The expected type comes from property 'invoke' which is declared here on type 'StateNodeConfig<PushStatusContext, {}, PushStatusEvent>'
[npm] src/app/shared/services/push-notification/push-notification.state.ts:79:8 - error TS2322: Type 'AssignAction<{ isToggling: true; shouldBeEnabled: false; }, PushStatusEvent>' is not assignable to type 'SingleOrArray<Action<PushStatusContext, PushStatusEvent>>'.
[npm]   Type 'AssignAction<{ isToggling: true; shouldBeEnabled: false; }, PushStatusEvent>' is not assignable to type 'string'.
[npm] 79                                                entry: assign({
[npm]                                                   ~~~~~
[npm]   node_modules/xstate/lib/types.d.ts:304:5
[npm]     304     entry?: Actions<TContext, TEvent>;
[npm]             ~~~~~
[npm]     The expected type comes from property 'entry' which is declared here on type 'StateNodeConfig<PushStatusContext, {}, PushStatusEvent>'
[npm] src/app/shared/services/push-notification/push-notification.state.ts:83:8 - error TS2322: Type '{ id: string; src: () => Promise<any>; onDone: { actions: AssignAction<{ isEnabled: false; }, DoneInvokeEvent<any>>; target: string; }; onError: string; }' is not assignable to type 'SingleOrArray<StateMachine<any, any, any, { value: any; context: any; }> | InvokeConfig<PushStatusContext, PushStatusEvent>>'.
[npm]   Types of property 'onDone' are incompatible.
[npm]     Type '{ actions: AssignAction<{ isEnabled: false; }, DoneInvokeEvent<any>>; target: string; }' is not assignable to type 'string | TransitionConfig<PushStatusContext, DoneInvokeEvent<any>> | TransitionConfig<PushStatusContext, DoneInvokeEvent<...>>[]'.
[npm]       Types of property 'actions' are incompatible.
[npm]         Type 'AssignAction<{ isEnabled: false; }, DoneInvokeEvent<any>>' is not assignable to type 'SingleOrArray<Action<PushStatusContext, DoneInvokeEvent<any>>>'.
[npm]           Type 'AssignAction<{ isEnabled: false; }, DoneInvokeEvent<any>>' is not assignable to type 'string'.
[npm] 83                                                invoke: {
[npm]                                                   ~~~~~~
[npm]   node_modules/xstate/lib/types.d.ts:290:5
[npm]     290     invoke?: SingleOrArray<InvokeConfig<TContext, TEvent> | StateMachine<any, any, any>>;
[npm]             ~~~~~~
[npm]     The expected type comes from property 'invoke' which is declared here on type 'StateNodeConfig<PushStatusContext, {}, PushStatusEvent>'
```

**Reproduction**
```typescript
import { assign, interpret, Machine } from 'xstate'

export interface PushStatusSchema {
	states: {
		deregistered: {}
		registered: {
			states: {
				static: {}
				enabling: {}
				disabling: {}
			}
		}
	}
}

export type PushStatusEvent =
	| { type: 'REGISTER' }
	| { type: 'DEREGISTER' }
	| { type: 'ENABLE' }
	| { type: 'DISABLE' }

export interface PushStatusContext {
	isToggling: boolean
	shouldBeEnabled: boolean
	isEnabled: boolean
}

export function createPushStatusMachine(
	context: PushStatusContext,
	setPushState: (requestedState: boolean) => Promise<any>,
) {
	const pushStatusMachine = Machine<PushStatusContext, PushStatusSchema, PushStatusEvent>(
		{
			id: 'push-status',
			initial: 'deregistered',
			context: context,
			states: {
				deregistered: {
					on: {
						REGISTER: 'registered',
					},
				},
				registered: {
					initial: 'static',
					on: {
						DEREGISTER: {
							target: 'deregistered',
							actions: () => setPushState(false),
						},
					},
					states: {
						static: {
							entry: assign({
								isToggling: () => false,
							}),
							on: {
								ENABLE: 'enabling',
								DISABLE: 'disabling',
							},
						},
						enabling: {
							entry: assign({
								isToggling: () => true,
								shouldBeEnabled: () => true,
							}),
							invoke: {
								id: 'enabling-push',
								src: () => setPushState(true),
								onDone: {
									actions: assign({
										isEnabled: () => true,
									}),
									target: 'static',
								},
								onError: 'static',
							},
						},
						disabling: {
							entry: assign({
								isToggling: () => true,
								shouldBeEnabled: () => false,
							}),
							invoke: {
								id: 'disabling-push',
								src: () => setPushState(false),
								onDone: {
									actions: assign({
										isEnabled: () => false,
									}),
									target: 'static',
								},
								onError: 'static',
							},
						},
					},
				},
			},
		},
	)

	const machine = interpret(pushStatusMachine)
	machine.start()

	return machine
}
```

**Additional context**
xstate version: 4.12.0

**Comment by davidkpiano** [comment]
The workaround for this (as mentioned [in the docs](https://xstate.js.org/docs/guides/context.html#typescript)) is to add the context type as a generic param: 

```js

entry: assign<PushStateContext>({
  // ...
})
```

https://codesandbox.io/s/zen-northcutt-5r8dp?file=/src/index.ts

**Comment by RafaelKr** [comment]
Thank you very much for that incredibly quick response! It's working now.
